android/src/main/java/com/orientationdirector/implementation/OrientationDirectorImpl.kt
ios/OrientationDirector.mm
ios/implementation/OrientationDirectorImpl.swift

Currently this module doesn't follow the screenOrientation or the UISupportedInterfaceOrientation settings.
On iOS, at start time, supportedInterfaceOrientations is overridden with the following value: UIInterfaceOrientationMask.all, therefore the Info.plist value is useless and the app doesn't act accordingly.
On Android we don't override the screenOrientation value, although before the isLocked feature, the interface orientation on js would follow the device orientation incorrectly. Now it can't follow the device orientation since there is a condition that returns if isLocked is true and we compute its value at start time based on the screenOrientation setting.
To fix this issue on iOS, we read the Info.plist value, combine each UIInterfaceOrientationMask value and set the …

Bugfix - Wrong interface orientation behaviour at start time

---

android/src/main/java/com/orientationdirector/implementation/OrientationDirectorImpl.kt
android/src/main/java/com/orientationdirector/implementation/OrientationDirectorUtilsImpl.kt

I've written the initInitialOrientation logic from scratch, leveraging a leaner implementation that uses the display current rotation to convert it in a given Orientation.
This approach is cleaner and more correct since the old implementation relied upon requestOrientation that is setting based and from the deviceOrientation, although at init phase we haven't got any recorded device orientation yet.
I've also renamed the initialScreenOrientation to something more appropriate like in iOS.

Bugfix - Android screen orientation locked breaks initial interface orientation value

---

android/src/main/java/com/orientationdirector/implementation/OrientationAutoRotationObserver.kt
android/src/main/java/com/orientationdirector/implementation/OrientationDirectorImpl.kt
android/src/main/java/com/orientationdirector/implementation/OrientationDirectorUtilsImpl.kt

I've created a new class: OrientationAutoRotationObserver that implements ContentObserver and checks whether autoRotation setting is changed.
This value is then used inside adaptInterfaceTo method to check if interface can follow device rotation.
Note: an issue still persists and is the following:
If the user disables autoRotation and uses the icon that appears in the bottom bar whenever the device is in landscape, then there is no way i found to listen to that change and update interface orientation value.

Bugfix - android interface orientation value changes even with auto rotation off

---

android/src/main/java/com/orientationdirector/OrientationDirectorModule.kt
android/src/main/java/com/orientationdirector/implementation/OrientationDirectorImpl.kt
android/src/oldarch/OrientationDirectorSpec.kt
example/src/App.tsx
src/NativeOrientationDirector.ts
src/RNOrientationDirector.ts
src/index.tsx
src/types/AutoRotation.enum.ts

This PR adds a new ReactMethod: isAutoRotationEnabled and updates the JS side to implement it for Android.
The RNOrientationDirector class leverages the AutoRotation enum to return a UNKNOWN in iOS, since we can't access this kind of value.

Feature -  Android expose autorotation status to js

---

android/src/main/java/com/orientationdirector/OrientationDirectorModule.kt
android/src/main/java/com/orientationdirector/implementation/OrientationDirectorImpl.kt
android/src/oldarch/OrientationDirectorSpec.kt
example/ios/Podfile.lock
example/src/App.tsx
ios/OrientationDirector.mm
ios/implementation/OrientationDirectorImpl.swift
ios/implementation/OrientationDirectorUtils.swift
src/NativeOrientationDirector.ts
src/RNOrientationDirector.ts

This PR implements a new method called: resetSupportedInterfaceOrientations that reverts the current setup to the initial one: activity's screenOrientation or info.plist UISupportedInterfaceOrientations.

Feature - reset to initial supported interface orientation

---

ios/implementation/OrientationDirectorImpl.swift

This PR implements a missing check in adaptInterfaceTo method.
Currently this method executes an interface orientation value update even when the device orientation is not supported, therefore there is a bug in which we see the interface orientation value getting updated to a wrong value even tho the actual interface is not updating to match it.

Bugfix - iOS missing check if deviceOrientation is actually supported

---

android/src/main/java/com/orientationdirector/implementation/OrientationDirectorImpl.kt
android/src/main/java/com/orientationdirector/implementation/OrientationDirectorUtilsImpl.kt
ios/OrientationDirector.mm
ios/implementation/OrientationDirectorImpl.swift
ios/implementation/OrientationDirectorUtils.swift

This PR resets the Orientation computations so that the following statements is true:
"When the device is in landscape left, then the interface orientation is rotate on the right and viceversa, both in iOS and Android"

Bugfix: interface orientation should match bottom bar position

---

ios/OrientationDirector.mm

This PR switches RCT_EXPORT_BLOCKING_SYNCHRONOUS_METHOD with RCT_EXPORT_METHOD.

Bugfix: wrong MACRO used for resetSupportedInterfaceOrientations

---

ios/OrientationDirector.mm

This PR aims to improve the current ios native code structure to align it to the latest Turbo Modules [guide](https://github.com/reactwg/react-native-new-architecture/blob/main/docs/turbo-modules.md#turbo-native-modules).
So I've implemented the following changes:
- I've removed all ifdef that defined methods signatures based on arch type. We don't need it;
- I've updated rejecter naming to reject, because rejecter isn't recognised by Codegen and it breaks at runtime;

feat: improve ios native structure

---

README.md
android/src/main/java/com/orientationdirector/implementation/EventManager.kt
android/src/main/java/com/orientationdirector/implementation/LifecycleListener.kt
android/src/main/java/com/orientationdirector/implementation/Orientation.kt
android/src/main/java/com/orientationdirector/implementation/OrientationDirectorModuleImpl.kt
android/src/main/java/com/orientationdirector/implementation/OrientationSensorsEventListener.kt
android/src/main/java/com/orientationdirector/implementation/SensorListener.kt
android/src/main/java/com/orientationdirector/implementation/Utils.kt
src/types/Orientation.enum.ts

This PR implements a new device orientation setup that aligns with iOS through the [Android Sensor Framework](https://developer.android.com/develop/sensors-and-location/sensors/sensors_overview).
We've dropped the **OrientationEventListener** implementation in favour of a **SensorEventListener** that leverages both accelerometer and magnetometer sensors.
Their readings are then handled by the `SensorManager.getRotationMatrix` and `SensorManager.getOrientation` methods to obtain useful orientation angles that we can use to compute the device orientation at runtime.

feat: implement missing device orientations on android

---

README.md
src/RNOrientationDirector.ts

This PR adds a new method to the public API: `isLockableOrientation`.
This method can be used with listenToDeviceOrientation, for example, to properly check if a given orientation can be used with lockTo, since we can't lock interface orientation to face up, face down or unknown.

feat(js): add is lockable orientation method

---

ios/implementation/OrientationDirectorImpl.swift
ios/implementation/Utils.swift

This PR removes manual interface orientation computation on device orientation changes.
It switches it for the built in native API.

refactor(iOS): remove manual interface orientation computation

---

README.md
src/RNOrientationDirector.ts
src/index.tsx
src/types/OrientationType.enum.ts

This PR aims to improve lockTo method usability by:
1. Document that there is a difference between device orientation and interface orientation;
2. Provide a second parameter that discriminate the type of orientation value provided;
This is necessary because when we supply an orientation value that isn't explicit, for example when using listeners, if such value is either landscapeRight or landscapeLeft and tied to the device orientation, we need to switch them to match the interface orientation expectation.

feat(js): extend lockTo method with additional parameter

---

android/src/test/java/com/orientationdirector/implementation/OrientationDirectorModuleImplTest.kt

This PR fixes the latest test introduced for the lockTo enhancement: **assert_interface_orientation_matches_locked_to_landscape**

fix(android): failing test

---

ios/implementation/EventManager.swift
ios/implementation/OrientationDirectorImpl.swift
ios/implementation/SensorListener.swift
ios/implementation/Utils.swift

This PR runs [swiftlint](https://github.com/realm/SwiftLint?tab=readme-ov-file#swift-package-command-plugin) to lint and fix all iOS files.

style(iOS): swiftlint lint --fix

---

.github/workflows/pr.yml

This PR updates the pr workflow to run only on review submission with approved status.

ci: improve pr workflow to run only on pr review approved

---

.github/workflows/release.yml

This PR creates a new workflow to automate the release process.
It allows us to run a manual release with an optional dry-run flag to test it out first.
To properly function, it needs a github app with a npm automation token.

ci: create release workflow

---

.github/workflows/release.yml
package.json
yarn.lock

This PR fixes the following error:
```
Internal Error: Assertion failed: Expected workspace react-native-orientation-director-expo-plugin (/home/runner/work/react-native-orientation-director/react-native-orientation-director/package.json) to have been resolved. Run "yarn install" to update the lockfile
```
by refreshing yarn.lock.
It also removes the -R flag from the release.yml file to avoid recursive print of the working directory.

ci: remove recursive print and fix workspace issue

---

package.json
yarn.lock

This PR fixes the current `lint` command crashing due to expo pulling `typescript-eslint` dependencies incompatible with react-native's ones.

fix: broken lint due to expo deps

---

README.md
android/src/main/java/com/orientationdirector/implementation/ConfigurationChangedBroadcastReceiver.kt
android/src/main/java/com/orientationdirector/implementation/OrientationDirectorModuleImpl.kt
example/android/app/src/main/AndroidManifest.xml
example/android/app/src/main/java/com/orientationdirectorexample/MainActivity.kt
plugin/__tests__/__snapshots__/withRNOrientationMainActivity.spec.ts.snap
plugin/__tests__/fixtures/MainActivity.kt
plugin/__tests__/withRNOrientationMainActivity.spec.ts
plugin/src/index.ts
plugin/src/withRNOrientationMainActivity.ts

This PR fixes #58 that currently affect the library, specifically: when the user disables the `auto rotation` feature, the system prompts the user with an helpful icon that the user can tap to manually rotate the interface to the desired orientation, based on the last device orientation.
This means tho, that currently we don't intercept it and do not update the interface accordingly.
This PR implements a new Broadcast Receiver that intercepts the `MainActivity`.`onConfigurationChanged` call through a custom explicit intent.
It also means that the developer has to update its MainActivity with the following onConfigurationChanged override:
```kotlin
override fun onConfigurationChanged(newConfig: Configuration) {
super.onConfigurationChanged(newConfig)
val orientationDirectorCustomAction = …
```

fix(android): interface orientation listener not working with manual rotation

---

README.md
plugin/__tests__/__snapshots__/withRNOrientationMainActivity.spec.ts.snap
plugin/__tests__/fixtures/MainActivityWithConfigurationImport.kt
plugin/__tests__/fixtures/MainActivityWithIntentImport.kt
plugin/__tests__/withRNOrientationMainActivity.spec.ts
plugin/src/withRNOrientationMainActivity.ts

This PR fixes #60 by implementing the missing logic for the intent and configuration imports in Android using the expo plugin.
It skips the update if the imports already exist.

fix(plugin): missing intent and configuration imports logic

---

android/src/main/java/com/orientationdirector/implementation/ConfigurationChangedBroadcastReceiver.kt

This PR implements a missing check to avoid calling: `context.unregisterReceiver` if the receiver was not registered yet.
It should fix #63, even tho I was not actually able to reproduce it yet.

fix(android): missing check before unregistering receiver

---

README.md

This PR fixes #69 by mentioning the proper file: `AppDelegate.mm` to update during library setup.

fix: wrong app delegate file mention

---

example/ios/Podfile.lock
ios/implementation/OrientationDirectorImpl.swift
ios/implementation/Utils.swift

This PR fixes #75 by providing the right value type to the `UIDevice.current.setValue` method, from `UIInterfaceOrientationMask` to `UIInterfaceOrientation`.
It builds upon #74, so we need to merge that one first, do a rebase and then merge this one.

fix(iOS): ios 15 doesn't lock the interface using provided methods
